name: Pipeline QA - Treino

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v6

      - name: Exibir mensagem
        run: echo "Pipeline de QA iniciado"

      - name: Validar arquivo README
        run: test -f README.txt

      - name: Finalizar
        run: echo "Pipeline executado com sucesso"
